CartoDB/deep-insights.js

spec/widgets/category/stats_view.spec.js, src/widgets/category/model.js, src/widgets/category/models/categories_collection.js, src/widgets/category/stats/stats_template.tpl, src/widgets/category/stats/stats_view.js
Basically it adds "TOP" word only when "Other" value is available in the data collection.
Fixes #7.
REVIEWER: @javierarce
=> Adding top word when there are Other categories present in aggregated widget

themes/scss/widgets/default.scss, themes/scss/widgets/list.scss
=> fix margins in fake list

spec/dashboard-info-view.spec.js
=> Fix dashboard info view specs

examples/populated-places.html, spec/widgets/standard/loader-view.spec.js, src/widgets/standard/widget-loader-view.js, styleguide/elements.html, styleguide/layout-loading.html, themes/scss/widgets/default.scss, themes/scss/widgets/loader.scss, themes/scss/widgets/themes/light.scss
=> change template

themes/scss/map/canvas.scss, themes/scss/map/dashboard-info.scss
=> fix blue bar

examples/time-series-widget.html, examples/torque-time-series-widget.html, package.json, spec/widgets/category/category-widget-model.spec.js, spec/widgets/category/content-view.spec.js, spec/widgets/category/items-view.spec.js, spec/widgets/category/options-view.spec.js, spec/widgets/category/search-title-view.spec.js, spec/widgets/category/stats-view.spec.js, spec/widgets/formula/content-view.spec.js, spec/widgets/histogram/content-view.spec.js, spec/widgets/list/content-view.spec.js, spec/widgets/time-series/content-view.spec.js, spec/widgets/time-series/torque-content-view.spec.js, spec/widgets/time-series/torque-time-slider-view.spec.js, src/widgets/time-series/torque-header-view.js
Resolves #6 
Resolved #34 
hopefully once-and-for-all.
@rochoa can you review? cc @alonsogarciapablo
=> Fix time-series torque widget

package.json, src/dashboard-info-view.tpl, src/widgets/category/paginator/paginator-template.tpl, src/widgets/category/title/search-title-template.tpl, src/widgets/histogram/histogram-title-template.tpl, styleguide/layout-loading.html
This PR also updates the CartoIcon names (removes the extra dash)
cc: @xavijam
=> Update CartoAssets to 0.1.20 

spec/widgets/standard/widget-loader-view.spec.js, src/widgets/standard/widget-loader-view.js
Seems like model is dataviewModel itself:
https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/widget-view.js#L25
RW: @javierarce
=> Fix problem related with widget loader view

spec/widgets-service.spec.js, src/widgets-service.js
@xavijam this is the bug when creating category widgets. I didn't change the spec
=> fixed cat widget

examples/populated-places-local.html, examples/populated-places.html, examples/time-series-widget.html, examples/torque-time-series-widget.html, spec/create-dashboard.spec.js, spec/widgets-service.spec.js, src/create-dashboard.js, src/dashboard-sidebar-view.js, src/widgets-service.js
Resolves #94 
@javierarce review plz :wink:
=> Post public-widgets-api fixes

spec/widgets-service.spec.js, src/widgets-service.js
timeseries need more data that we were sending.
=> fixed timeseries

spec/widgets/formula/content-view.spec.js, src/widgets/formula/content-view.js, src/widgets/formula/template.tpl
Fixes #103.
CR: @viddo 
cc @saleiva
=> Rendering formula value although widget is collapsed

.gitignore, spec/widgets/category/options-view.spec.js, src/widgets/category/options/options-template.tpl, src/widgets/category/options/options-view.js
=> category none fix

src/widgets/time-series/content-view.js, src/widgets/time-series/torque-histogram-view.js
=> fixed time series with torque

package.json, spec/widgets-service.spec.js, src/widgets-service.js
Fixes https://github.com/CartoDB/deep-insights.js/issues/105
cc @viddo @alonsogarciapablo @javisantana
=> Suffix and prefix attributes are not being populated 

src/widgets/category/list/item/item-clickable-template.tpl, src/widgets/category/list/item/item-unclickable-template.tpl, src/widgets/category/list/item/search-item-clickable-template.tpl, themes/scss/widgets/themes/light.scss
=> Updating category items list names to the correct size and make them use Typography styles on cartoassets

package.json, themes/scss/widgets/text-elements.scss
=> Updating CartoAssets and CartoDB.js versions within package.json

package.json
https://github.com/CartoDB/cartodb.js/commit/94bb6f37f3b1a948bda3d59d12d60b94cbe0125d from https://github.com/CartoDB/cartodb.js/pull/1071
@javierarce
=> Fixes type of category dataview model

spec/dashboard-menu-view.spec.js, src/dashboard-menu-view.js, src/dashboard-menu-view.tpl, themes/scss/entry.scss, themes/scss/map/canvas.scss, themes/scss/map/dashboard-info.scss
@xavijam  could you take a look?
=> 126 change menu

src/widgets/histogram/chart.js, src/widgets/time-series/torque-histogram-view.js, themes/scss/widgets/themes/light.scss
After some thoughts, I feel the solution of adding a modifier class works ok, because you don't need to add colors in the JS views, only the class, and colors will be defined in the CSS. What do you think? 
cc @piensaenpixel @viddo
Fixes #135
=> Adding proper color to torque histogram widget

package.json, spec/create-dashboard.spec.js, spec/spec-helper.js
=> Add missing bbox bounds to vizjson used in tests

spec/widgets/formula/content-view.spec.js, src/widgets/formula/template.tpl
@xavijam - Related: https://github.com/CartoDB/deep-insights.js/issues/143
=> remove tags

package.json, spec/widgets/time-series/torque-time-slider-view.spec.js, src/widgets/time-series/torque-histogram-view.js, src/widgets/time-series/torque-time-slider-view.js
this PR needs other pr to be merged:
- https://github.com/CartoDB/torque/pull/255
- https://github.com/CartoDB/cartodb.js/pull/1091
also needs a new version of the tiler with this commit: https://github.com/CartoDB/Windshaft/commit/d7c39419d2f6849e049d8606d466081ccf4a4b98
cc @viddo
=> fixes time slider with torque to work in the same way than other widgets

src/widgets/category/title/search-title-template.tpl, src/widgets/formula/template.tpl, src/widgets/histogram/content.tpl, themes/scss/entry.scss, themes/scss/widgets/text-elements.scss
@javierarce could you take a look?
Related - https://github.com/CartoDB/deep-insights.js/issues/177
=> use helper

themes/scss/widgets/filter.scss
=> fix missing merge

src/dashboard-menu-view.tpl, src/widgets/category/list/item/item-clickable-template.tpl, src/widgets/category/list/item/item-unclickable-template.tpl, src/widgets/category/list/item/search-item-clickable-template.tpl, src/widgets/category/options/options-template.tpl, src/widgets/category/paginator/paginator-template.tpl, src/widgets/category/paginator/search-paginator-template.tpl, src/widgets/category/stats/stats-view.js, src/widgets/formula/template.tpl, src/widgets/histogram/content.tpl
=> move helper

src/widgets/time-series/histogram-view.js
=> fixes range filter

src/widgets/category/title/search-title-template.tpl
@xavijam take a look
related: https://github.com/CartoDB/deep-insights.js/issues/186
=> fix apply button

src/widgets/formula/template.tpl, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js, themes/scss/widgets/default.scss
could you take a look @javierarce 
Reference - https://github.com/CartoDB/deep-insights.js/issues/185
=> 185 minor fix ui

examples/airbnb_and_closest_metro.html, package.json, spec/create-dashboard.spec.js, src/create-dashboard.js
Basically, this PR is using the code of this [PR](https://github.com/CartoDB/cartodb.js/pull/1104) from CartoDB.js.
cc @viddo @javisantana @acanimal @alonsogarciapablo @javierarce
=> Skip vis map instantiation and request it when dataviews are generated

package.json, spec/create-dashboard.spec.js, src/create-dashboard.js
It really fixes #190 issue, but needs [these changes](https://github.com/CartoDB/cartodb.js/pull/1106) in CartoDB.js.
CR: @javisantana
=> Added method to re-center map to origin position when there is any widget

package.json
=> Pointing to last CartoDB.js#v4 commit

src/widgets/histogram/content-view.js, src/widgets/histogram/content.tpl, src/widgets/histogram/placeholder.tpl, themes/scss/widgets/chart.scss
=> Fixing histogram loading state

spec/widgets/histogram/content-view.spec.js, src/widgets/histogram/content-view.js
Fixes CartoDB/cartodb.js#1069.
It's not the most elegant solution to the problem, but it's the quickest solution I could think off.
@acanimal can you please take a look? Thanks!
=> Set internal histogram dataview attributes silently

examples/populated-places.html, spec/widgets/formula/content-view.spec.js, src/widgets-service.js, src/widgets/formula/content-view.js, src/widgets/formula/template.tpl
=> Added description to the formula widget

package.json, spec/widgets/histogram/content-view.spec.js, src/widgets/histogram/content-view.js
This should be merged after CartoDB/cartodb.js#1114.
cc: @javisantana
=> Histogram widget view enables and disables histogram dataview filters

spec/widgets/histogram/chart.spec.js, spec/widgets/histogram/content-view.spec.js, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js, src/widgets/time-series/torque-histogram-view.js
cc @viddo in case I miss something for time histogram.
Fixes #166.
=> Refresh histogram widget when bins attribute is updated

themes/scss/widgets/default.scss, themes/scss/widgets/filter.scss
@xavijam after remove metada in public view we need fix some margins, could you take a look?
=> fix margins

src/widgets/time-series/torque-reset-render-range.tpl, themes/scss/widgets/default.scss, themes/scss/widgets/time-series.scss
Related - https://github.com/CartoDB/deep-insights.js/issues/217
=> 217 fix time series

package.json
Updating CartoDB.js dependency in order to have latest changes from there.
cc @acanimal @viddo
=> Updating last changes from CartoDB.js

spec/dashboard-below-map-view.spec.js, src/dashboard-below-map-view.js
Fixes #240 , by changing the visibility on widgets add/removal 
@xavijam @javierarce can any of you review?
=> Fixes creating a time-series model dynamically doesn't render the widget 

package.json, spec/widgets/widget-error-view.spec.js, spec/widgets/widget-loader-view.spec.js, src/widgets/widget-error-view.js, src/widgets/widget-loader-view.js
Error state wasn't working, due to a problem with model attribute setting and loader view now is listening to `loaded` event  (https://github.com/CartoDB/cartodb.js/pull/1129/files#r53784263).
CR: @javisantana 
Fixes #236 using https://github.com/CartoDB/cartodb.js/pull/1129/files.
=> Fixing problems with the loader and the error state

package.json
cc @javierarce, nothing to review, but just in case :dancer:
=> Pointing to last CartoDB.js commit

examples/torque-time-series-widget.html
=> Expose dashboard object on window

package.json, spec/widgets/category/items-view.spec.js, src/widgets/category/list/items-view.js, src/widgets/category/list/search-items-view.js
Related with https://github.com/CartoDB/cartodb.js/pull/1134. And finally fixes #247.
cc @javisantana
=> Fixing problems with search results

package.json
Fixes #249, FINALLY!
cc @javisantana
=> Updating CartoDB.js

examples/time-series-widget.html, examples/torque-time-series-widget.html, package.json, spec/widgets/time-series/torque-time-slider-view.spec.js, src/widgets-service.js, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js, src/widgets/time-series/content-view.js, src/widgets/time-series/histogram-view.js, src/widgets/time-series/torque-histogram-view.js, src/widgets/time-series/torque-time-slider-view.js
Resolves #244 updates the x-scale and chart on bins/start/end change.
@javierarce can you review please? minor change to the histogram chart, should be straight forward
=> 244 fix time series update

spec/widgets/time-series/torque-time-slider-view.spec.js, src/widgets/time-series/torque-time-slider-view.js
There was a glitch that until the data returned the time-slider is
visible and animated to the place of the range selector
cc @xavijam
=> Fix time slider on range change

src/dashboard-menu-view.tpl
Fixes CartoDB/cartodb#6649
CR @xavijam 
cc @juanignaciosl
=> Display HTML in description for embed visualizations

package.json
This new version contains all the vector stuff \o/
=> Bumped version of CartoDB.js

spec/widgets/category/options-view.spec.js, src/widgets/category/options/options-template.tpl, src/widgets/category/options/options-view.js
Example, selecting BRA category:
- Before (appearing "SELECT ALL"):
- Now (appearing "NONE SELECTED"):
CR: @viddo
=> When a category is selected but it doesn't appear in the current data, "none selected" should appear

package.json, spec/widgets/category/options-view.spec.js, src/widgets/category/options/options-template.tpl, src/widgets/category/options/options-view.js
This should fix the problem we have seen today in the last PoC.
@saleiva @AbelVM
=> Fixing problem with accepted categories not present in current data

src/widgets/category/list/items-view.js, src/widgets/category/options/options-view.js
Fixes #250 
@AbelVM @piensaenpixel
=> Fixing problems with category list behaviour and related stats

src/widgets/histogram/chart.js, themes/scss/widgets/themes/light.scss
=> Don't hide axis tip when user selects a range

package.json
We need this [fix](https://github.com/CartoDB/cartodb.js/pull/1183) from CartoDB.js in CartoDB and Deep-insights, basically.
=> Updated CartoDB.js#v4

src/dashboard-menu-view.tpl
Related - https://github.com/CartoDB/deep-insights.js/issues/274
could you take a look @xavijam ?
=> fix long map name

src/widgets/category/stats/stats-view.js, src/widgets/formula/template.tpl, src/widgets/histogram/content.tpl, src/widgets/list/content-template.tpl
Related - https://github.com/CartoDB/deep-insights.js/issues/275
=> add margin-top

src/widgets/category/list/item/item-clickable-template.tpl, src/widgets/category/list/item/item-unclickable-template.tpl
=> fix long texts

themes/scss/widgets/canvas.scss, themes/scss/widgets/default.scss, themes/scss/widgets/info.scss
fixes #283
@xavijam could you take a look
=> fix tablet view

src/dashboard-menu-view.tpl, themes/scss/widgets/canvas.scss
=> fix mobile navigation

package.json
=> Updates cartodb.js with latest v4 commit

examples/populated-places.html, spec/widgets/widgets-collection.spec.js, src/dashboard-sidebar-view.js, src/widgets-service.js, src/widgets/widgets-collection.js
And if any widget changes its order, list will be rendered.
There will be another for CartoDB Editor in minutes, that's for you @viddo :dancer: 
cc @saleiva @AbelVM
=> Render widgets list sorted by order

src/widgets/category/list/item/search-item-clickable-template.tpl
=> Fixed text ellipsis wrapping for search items within category widget

package.json
Ditto https://github.com/CartoDB/cartodb.js/pull/1199
cc @javisantana
=> Use main branch for cartodb.js as dependency version

spec/widgets/histogram/chart.spec.js, src/widgets/dropdown/template.tpl, src/widgets/dropdown/widget-dropdown-view.js, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js
=> added switch to enable histogram normalization

themes/scss/widgets/chart.scss, themes/scss/widgets/list.scss
@javierarce could you take a look?
=> fix jump height

grunt-tasks/browserify.js, src/index_standalone.js
=> added standalone index to have deepInsights scope inside cartodb one

src/widgets/histogram/chart.js
part of the work needed to serialize filters
=> serialize filters to the model

package.json
=> Use latest browserify versions to rely on factor-bundle plugin

spec/widgets/category/item-view.spec.js, src/widgets/category/list/item/item-clickable-template.tpl, src/widgets/category/list/item/item-view.js, src/widgets/category/list/item/search-item-clickable-template.tpl, src/widgets/histogram/chart.js, themes/scss/widgets/themes/light.scss
Histograms and categories become blue when being selected. This is expected to improve the speed on detecting that a filter is being applied.
=> Blue when selected

spec/api/create-dashboard.spec.js, src/api/create-dashboard.js, src/api/dashboard.js, src/dashboard-view.js, src/widgets-service.js
Now the map position (center coordinates and zoom level) are returned as part of the state object, and as a shareable url.
@javisantana
=> Adds setters and getters to the map state

spec/widgets/category/item-view.spec.js, src/api/create-dashboard.js, src/api/dashboard.js, src/widgets-service.js, src/widgets/category/category-widget-model.js, src/widgets/category/list/items-view.js, src/widgets/histogram/content-view.js, src/widgets/histogram/histogram-title-view.js, src/widgets/histogram/histogram-widget-model.js, src/widgets/widget-model.js, src/widgets/widgets-collection.js
=> Category & Histogram state set/get

src/widgets/auto-style/auto-styler.js
Fixes https://github.com/CartoDB/cartodb/issues/8239
=> Repairs width parsing on autostyling

themes/scss/widgets/canvas.scss, themes/scss/widgets/default.scss, themes/scss/widgets/list.scss
@xavijam could you take a look? ... sorry ...
=> fix responsive view

src/api/dashboard.js, src/widgets/histogram/content-view.js, src/widgets/histogram/histogram-widget-model.js, src/widgets/widget-model.js
* Histogram bars are not passed in the state if they haven't been changed
* Map state will not be reported if the position hasn't changed from 1% of its default position.
=> Default states fixes

src/widgets/histogram/chart.js
Fixes #400 , related to https://github.com/CartoDB/cartodb/issues/8320
@javisantana
=> Fixes bars not showing in responsive, small histogram

src/dashboard-menu-view.tpl, src/dashboard-sidebar-view.js, themes/scss/map/dashboard-info.scss, themes/scss/widgets/default.scss
Fix the problem with the scroll  and resize the window, and minor ui adjust
cc/@saleiva
=> fix problem with scroll

src/widgets/category/paginator/search-paginator-view.js
=> Only show points on search pagination if pages > 1

spec/formatter.spec.js, src/formatter.js
=> Flexible precision for small and negative values

themes/scss/map/dashboard-info.scss
=> Fixed no line-break behaviour in embed description

src/widgets/auto-style/histogram.js
@saleiva please review. There were some changes I wanted to do anyway which was mainly switching the clustered and skewed ramps. I did that and also updated all ramps with current names.
=> updating color palettes with new names

src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js
CR @javierarce @xavijam 
This was motivated by some debugging I did, where I noticed several repeated calls
=> Removes unnecessary function and avoids unnecessary calls to updateStats when changing the range on the histogram

spec/widgets/time-series/torque-content-view.spec.js, spec/widgets/time-series/torque-time-slider-view.spec.js, themes/scss/widgets/error.scss
Preventing this error basically:
cc @piensaenpixel
=> Fixed widget error in builder

spec/widgets/time-series/torque-content-view.spec.js, spec/widgets/time-series/torque-time-slider-view.spec.js, src/dashboard-sidebar-view.js, themes/scss/widgets/canvas.scss
@saleiva take a look
cc @xavijam 
Fix - https://github.com/CartoDB/cartodb/issues/8201
=> fix scroll

src/widgets/time-series/time-series-header-view.js, src/widgets/time-series/time-series-header.tpl
Fixes https://github.com/CartoDB/cartodb/issues/9895
=> Fixed problem with time-series header selection info

src/api/create-dashboard.js, src/widgets-service.js, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js, src/widgets/histogram/histogram-widget-model.js, src/widgets/time-series/content-view.js, src/widgets/time-series/histogram-view.js, src/widgets/time-series/time-series-widget-model.js
This PR fixes #445.
CR @xavijam
=> Histogram state

themes/scss/map/canvas.scss, themes/scss/map/dashboard-info.scss
@nobuti could you take a look? this is a temporal fix for responsive view
cc/ @saleiva
=> temporal fix for responsive view

spec/dashboard-view.spec.js, src/api/create-dashboard.js, src/dashboard-menu-view.js, src/dashboard-menu-view.tpl
This PR fixes the DI side for https://github.com/CartoDB/cartodb/issues/9532
cc @xavijam @piensaenpixel
=> Logo option.

themes/scss/widgets/list.scss
@nobuti could you take a look?
=> fix ellipsis

spec/widgets/category/content-view.spec.js, spec/widgets/formula/content-view.spec.js, spec/widgets/histogram/content-view.spec.js, src/api/create-dashboard.js, src/api/dashboard.js, src/widgets-service.js, src/widgets/category/content-view.js, src/widgets/formula/content-view.js, src/widgets/histogram/content-view.js, src/widgets/histogram/histogram-widget-model.js, src/widgets/widget-model.js
This PR fixes the state issues of #445, related to histogram mainly. 
Basically we are injecting the state form the url, so we need to perform some operations on the widgets when this happens. In the histogram widget it's way more complicated because there are two views acting on the same model. Also some issues related to the stats have been fixed.
This PR is a patch, we need to tackle a better approach for the histogram in the future.
cc @xavijam @javisantana
=> Fix state for histogram

themes/scss/widgets/list.scss
@nobuti could you take a look?
=> fix category search

themes/scss/widgets/themes/light.scss
@javierarce could you take a look?
Fix - https://github.com/CartoDB/cartodb/issues/9541
=> add active area

src/dashboard-sidebar-view.js
We need to show the scrollbar always by default in the sidebar. The plugin used doesn't allow that in a easy way AFAIK, only provides a css recipe: https://github.com/noraesae/perfect-scrollbar/wiki/FAQ#how-can-i-make-the-scrollbars-always-visible. The problem is we need to hide the scrollbar if the content is smaller than our container. In order to achieve it, we need to check if scroll is needed when widgets are added/removed, adding a selector to the container to manage the recipe written above. For that, instead the old fashioned `setInterval`, we are using the `MutationObserver` api. The (not as) bad part is that for ie10 users, the scroll is handle completely by the plugin.
I feel this is the right way to do it, but if you see ie10 users are important, let me know in order to make a …
=> Mutation observer to trigger actions everytime a widget is added or removed.

package.json
=> Update carto-colors package

grunt-tasks/scss.js, package.json, src/dashboard-sidebar-view.js
This PR updates the perfect scrollbar library to fix https://github.com/CartoDB/cartodb/issues/11190. You can read more about what it's included in the update here: https://github.com/nobuti/perfect-scrollbar/pull/1
=> Update perfect scrollbar dependency

src/api/create-dashboard.js
Related to https://github.com/CartoDB/cartodb.js/pull/1590.
=> createDashboard provides better error messages

src/widgets/category/paginator/paginator-view.js
See http://stackoverflow.com/questions/21661113/jquery-error-during-load-failed-to-execute-query-x-is-not-a-valid-selecto for details.
cc @xavijam
=> Jquery sizzle weird silent bug.

themes/scss/widgets/default.scss
=> fix loader in low resolutions view

themes/scss/widgets/default.scss
=> Fixed problem with overflow in widgets

spec/api/create-dashboard.spec.js, src/api/create-dashboard.js
related: https://github.com/CartoDB/cartodb.js/pull/1615
=> Changed method after adding widgets in CARTO.js

package.json, spec/api/dashboard.spec.js, src/api/dashboard.js
This PR saves centre and zoom to be consumed by the state definition model in Builder.
Related to https://github.com/CartoDB/cartodb/issues/11846
=> Augment map state

spec/widgets/widget-model.spec.js, src/api/create-dashboard.js, src/api/dashboard.js, src/widgets-service.js, src/widgets/widget-model.js
This PR implements the DI side of https://github.com/CartoDB/cartodb/issues/8468.
=> Autostyle aggregation

src/api/create-dashboard.js
Required for CartoDB/cartodb#11783.
Fixes https://github.com/CartoDB/cartodb/issues/11486.
=> Do not use bounds from state to magically adjust map zoom

themes/scss/entry.scss
=> Remove duplicated import

package.json, spec/widgets/time-series/torque-histogram-view.spec.js, src/widgets/histogram/chart.js, src/widgets/time-series/torque-header-view.js, src/widgets/time-series/torque-histogram-view.js, src/widgets/time-series/torque-time-slider-view.js, themes/scss/widgets/_time-slider.scss, themes/scss/widgets/themes/_light.scss
re: https://github.com/CartoDB/cartodb/issues/12180
tests pending
=> time-series: draggable histogram and click

spec/dashboard-below-map-view.spec.js, spec/widgets/time-series/content-view.spec.js, spec/widgets/time-series/torque-content-view.spec.js, src/widgets/time-series/content-view.js, src/widgets/time-series/content.tpl, src/widgets/time-series/time-series-header-view.js, src/widgets/time-series/time-series-header.tpl, src/widgets/time-series/torque-content-view.js, src/widgets/time-series/torque-header-view.js, src/widgets/time-series/torque-template.tpl
re: https://github.com/CartoDB/cartodb/issues/12446
- added layer reference to time-series, and torque widgets
- extended specs to make them pass
/cc @arianaescobar
=> time-series: add layer reference

spec/dashboard-below-map-view.spec.js, spec/widgets-service.spec.js, src/dashboard-below-map-view.js, src/widgets-service.js, src/widgets/time-series/time-series-widget-model.js
This PR is related to https://github.com/CartoDB/cartodb/issues/12571, solving the pertinent code in DI side.
=> Create torque widget only if layer has hasAnimationStyle attribute.

package.json, spec/formatter.spec.js, spec/widgets/histogram/chart.spec.js, spec/widgets/histogram/content-view.spec.js, spec/widgets/time-series/content-view.spec.js, spec/widgets/time-series/torque-time-slider-view.spec.js, src/formatter.js, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js, src/widgets/time-series/content-view.js
Related to https://github.com/CartoDB/cartodb/issues/12618
Related PRs:
- cartodb https://github.com/CartoDB/cartodb/pull/12622
- cartodb.js https://github.com/CartoDB/cartodb.js/pull/1719
=> hotfix: fix histograms data range change.

spec/widgets/time-series/torque-content-view.spec.js, spec/widgets/time-series/torque-histogram-view.spec.js, spec/widgets/time-series/torque-time-slider-view.spec.js, src/widgets/category/list/items-view.js, themes/scss/widgets/_list.scss
Fixes https://github.com/CartoDB/support/issues/890#issuecomment-325933518
Made under the Response Team umbrella.
=> Enable category selection for non dynamic widgets

src/data/analyses.js, src/locale/en.json
=> Add 'Unknown' analysis to locales

spec/formatter.spec.js, spec/widgets/histogram/chart.spec.js, spec/widgets/time-series/torque-time-slider-view.spec.js, src/formatter.js, src/widgets/histogram/chart.js
Implements https://github.com/CartoDB/cartodb/issues/12696
=> Date format in histograms

.eslintignore, .eslintrc.json, .hound.yml, Gruntfile.js, package.json, spec/widgets/list/content-view.spec.js, src/api/create-dashboard.js, src/api/dashboard.js, src/formatter.js, src/index_standalone.js, src/util/layer-colors.js, src/widgets/auto-style/histogram.js, src/widgets/category/category-widget-model.js, src/widgets/formula/content-view.js, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js, src/widgets/list/item-view.js, src/widgets/time-series/content-view.js, src/widgets/widget-model.js, styleguide/styleguide.js
Changes:
- Use eslint grunt-task instead of semistandard binary
- Update semistandard package to 11.0.0
- Remove semistandard config from package.json
- Fix .eslintignore file
- Update .eslintrc.json file
- Fix Gruntfile lint
- Fix various rules lint
- Add eslint to hound
NOTE: rule "no-mixed-operators" is escaped in eslint.
=> Improve lint task

package.json, spec/widgets/histogram/chart.spec.js, src/widgets/histogram/chart.js
Related to https://github.com/CartoDB/cartodb/issues/12658
Changes axis tip rendering to point to the center of buckets in date time-series.
=> Refactor axis code

package.json, src/widgets/histogram/chart.js
Found and related to https://github.com/CartoDB/cartodb/issues/12778
=> Fix vanishing handles

src/data/analyses.js, src/locale/en.json
This PR fixes https://my.trackjs.com/details/0bf166fff2074fd9b0dc7befc54dcbd1
=> Added DO multiple locale.

src/dashboard-menu-view.js, src/dashboard-menu-view.tpl, themes/scss/map/_dashboard-info.scss
This PR is related to https://github.com/CartoDB/cartodb/issues/12501.
Fixed CARTO logo on IE11.
=> Added scroll. And more <3 to IE11.

.travis.yml, package.json
Related to: https://github.com/CartoDB/cartodb.js/pull/1755
Update tests to new vizJSON format.
=> Fix layer sources

package.json, src/dashboard-sidebar-view.js, themes/scss/widgets/_canvas.scss
Related to: https://github.com/CartoDB/cartodb/issues/12184
Refactor widgets scrollbars.
Main PR: https://github.com/CartoDB/cartodb/pull/12877
=> Unify scrollbars

package.json
=> Bump cartodb.js

package.json
Related to: https://github.com/CartoDB/cartodb.js/issues/1796
=> Integrate remove-analysis-collection

package.json
This PR points to https://github.com/CartoDB/cartodb/pull/12981
=> Update cartodb.js reference for D3 reduced footprint

package.json
Point to `cartodb.js#v4.0.0-alpha.16`
=> Point to cartodb.js tag

package.json
Point to https://github.com/CartoDB/cartodb.js/pull/1843
=> Point to cartodb.js branch fix-preview-map

package.json, spec/widgets/time-series/torque-content-view.spec.js, spec/widgets/time-series/torque-histogram-view.spec.js, spec/widgets/time-series/torque-time-slider-view.spec.js
Related to: https://github.com/CartoDB/cartodb.js/issues/1837
=> Integrate extract-engine

grunt-tasks/jasmine.js, package.json, spec/index.html, spec/widgets/widget-view.spec.js, src/util/error-enhancer.js, src/widgets/widget-view.js
Integration ticket https://github.com/CartoDB/cartodb.js/issues/1855
----
=> carto.js public api integration

README.md, spec/widgets-service.spec.js, spec/widgets/widget-model.spec.js, src/widgets/widget-model.js
Related ticket: CartoDB/support#1135
=> Dataview enable always true, no matter layer visibility 

package.json, yarn.lock
re: https://github.com/CartoDB/cartodb/issues/13074
=> Add hover to UI Elements

package.json, src/util/error-enhancer.js, yarn.lock
https://github.com/CartoDB/cartodb.js/issues/1936
----
- Point to proper `carto.js` reference
- Return generic enhanced error if there's no entry for the error in the enhancement list.
=> Carto.js feedback fixes integration

package.json, spec/widgets/category/content-view.spec.js, spec/widgets/formula/content-view.spec.js, spec/widgets/histogram/content-view.spec.js, spec/widgets/time-series/content-view.spec.js, spec/widgets/time-series/torque-content-view.spec.js, src/widgets/category/title/search-title-template.tpl, src/widgets/category/title/search-title-view.js, src/widgets/formula/content-view.js, src/widgets/formula/template.tpl, src/widgets/histogram/content-view.js, src/widgets/histogram/content.tpl, src/widgets/time-series/content-view.js, src/widgets/time-series/content.tpl, src/widgets/time-series/torque-content-view.js, src/widgets/time-series/torque-template.tpl, yarn.lock
Related to: https://github.com/CartoDB/cartodb/issues/13122
=> Redesign node info in widgets

package.json
Related to: https://github.com/CartoDB/cartodb.js/issues/1954
=> Wax webpack

package.json, spec/widgets/histogram/content-view.spec.js, src/util/error-enhancer.js, src/widgets/histogram/chart.js, src/widgets/histogram/content-view.js
Related to https://github.com/CartoDB/cartodb/issues/13059
----
- Added dataview type to error enhancer.
- Point to proper cartodb.js branch.
=> Add dataview type to error enhancer

spec/dashboard-below-map-view.spec.js, spec/spec-helper.js, spec/widgets/category/content-view.spec.js, spec/widgets/category/search-title-view.spec.js, spec/widgets/formula/content-view.spec.js, spec/widgets/histogram/content-view.spec.js, spec/widgets/time-series/content-view.spec.js, spec/widgets/time-series/torque-content-view.spec.js, src/widgets-service.js, src/widgets/category/title/search-title-template.tpl, src/widgets/category/title/search-title-view.js, src/widgets/formula/content-view.js, src/widgets/formula/template.tpl, src/widgets/histogram/content-view.js, src/widgets/histogram/content.tpl, src/widgets/time-series/content-view.js, src/widgets/time-series/content.tpl, src/widgets/time-series/torque-content-view.js, src/widgets/time-series/torque-template.tpl, yarn.lock
Related to: https://github.com/CartoDB/cartodb/pull/13239#issuecomment-352463614
Apply some utility classes to center the node information vertically in the widget
=> Improve node info in widget

spec/dashboard-sidebar-view.spec.js, src/dashboard-sidebar-view.js
This PR renders added widgets on top of the existing ones, allowing to change the behaviour as mentioned in https://github.com/CartoDB/cartodb/pull/13249.
Please check the acceptance of https://github.com/CartoDB/cartodb/pull/13249 as the feature change is shared with Builder.
=> Make new widgets appear on top
