grunt-tasks/browserify.js
package.json
spec/dashboard-info-view.spec.js
spec/dashboard-view.spec.js
spec/windshaft/dashboard.spec.js
spec/windshaft/public-dashboard-config.spec.js
src/widgets/histogram/model.js
src/widgets/list/model.js
src/windshaft/dashboard.js
src/windshaft/filters/category.js

This allows to `npm link cartodb.js` without duplicating `backbone` within the generated bundle when using browserify's `--debug` flag.

Backbone dedupe

---

Gruntfile.js
grunt-tasks/verify-dependencies.js

This adds a grunt task to validate shared dependencies with cartodb.js.
In order to keep dependencies synced between two projects this will make test task to fail if dependencies mismatch.
Having dependencies in sync is important to not have different ones bundled into the final dist files. This reduces the size of bundles.

Verify dependencies

---

src/widgets/histogram/content-view.js

This PR fixes a possible bug introduced in this PR: https://github.com/CartoDB/deep-insights.js/pull/69/files#diff-073fbe94fcf07c28afc1f6287797a05dL328 
The issue is that the 'SELECTED' label after the number of elements selected by the histogram range is no longer appearing:
@piensaenpixel: I'm saying "possible" because I don't know if we removed it by mistake or not. Can you review this, please?

Bring back 'SELECTED' label 

---

examples/populated-places-local.html
examples/populated-places.html
package.json
spec/widgets-service.spec.js
spec/widgets/category/category-widget-model.spec.js
spec/widgets/category/content-view.spec.js
spec/widgets/category/items-view.spec.js
spec/widgets/category/options-view.spec.js
spec/widgets/category/search-title-view.spec.js
spec/widgets/category/stats-view.spec.js
spec/widgets/formula/content-view.spec.js
spec/widgets/histogram/content-view.spec.js
spec/widgets/histogram/histogram-widget-model.spec.js
spec/widgets/list/content-view.spec.js
spec/widgets/time-series/content-view.spec.js
spec/widgets/time-series/torque-content-view.spec.js
spec/widgets/time-series/torque-time-slider-view.spec.js
spec/widgets/widget-model.spec.js
src/widgets-service.js
src/widgets/category/category-widget-model.js
src/widgets/category/list/item/item-view.js
src/widgets/category/list/item/search-item-view.js
src/widgets/category/list/search-items-view.js
src/widgets/formula/content-view.js
src/widgets/widget-model.js

Allows to set `enabled`, `sync_on_data_change` and `sync_on_bbox_change` attrs, to control widgets behavior.
Also, piggy back for other minor fixes that are required for new editor:
@alonsogarciapablo related to the prev PR so you can probably review here too
cc @xavijam @javierarce

Allow override of the default sync settings

---

spec/widgets/formula/content-view.spec.js
src/widgets/formula/content-view.js

Fixes #161:
@viddo PTAL. Thanks!

Bring operation badget in formula widgets back!

---

examples/populated-places.html
package.json

Utilizes the fix from
https://github.com/CartoDB/cartodb.js/commit/dceb6d30dae3e8898eb284ba206
53d4f53e4a076 https://github.com/CartoDB/cartodb.js/pull/1095 which
uses the provided ID from the widget definition if available, or
fallback on a generated temporary one (dataview-type + cid)
@acanimal

Fix undefined widget ids

---

spec/widgets/histogram/chart.spec.js
src/widgets/histogram/chart.js
src/widgets/histogram/content-view.js

This PR introduces a change that allows to calculate and store the original vertical scale (`yScale`), fixing a bug with the representation of data.
Now the `yScale` is calculated once and stored. The calls to retrieve more data are represented based on the original scale. The scale can be updated (using the `updateYScale` method) or reverted to its original values (with `resetYScale`).
CR: @javisantana

Fixes histogram normalisation bug

---

examples/populated-places.html
spec/widgets/category/content-view.spec.js
spec/widgets/formula/content-view.spec.js
spec/widgets/histogram/content-view.spec.js
src/widgets-service.js
src/widgets/category/content-view.js
src/widgets/formula/content-view.js
src/widgets/formula/template.tpl
src/widgets/histogram/content-view.js
src/widgets/histogram/content.tpl
src/widgets/widget-model.js

But if you want to show them, just set `show_stats` attribute to true.
I've found it easy to add, did I miss something? Missing any test?
---
---
CR: @viddo

Hide widgets stats by default

---

spec/widgets/histogram/content-view.spec.js
src/widgets/histogram/content-view.js

There was a race condition and the zoom/clear feature of the histogram widget wasn't working properly when fetching data from GeoJSON tiles. This PR fixes that. I verified that things are still working :ok_hand: on the raster world with these changes.
@javierarce could you please CR? Thanks!
Fixes CartoDB/cartodb.js#1089

Fixes histogram zooming

---

spec/widgets/histogram/content-view.spec.js
src/widgets-service.js
src/widgets/histogram/chart.js
src/widgets/histogram/content-view.js

Basically I didn't take into account `originalData` for the shadow bars, and these were using the same data that the current bars have.
I've tried to not "touch" how things are right now, the main change is that `originalData` is now a `Backbone.Collection`, which provides the data to the 'shadowBars'.
If there is any *bins* change, `originalData` would be emptied and then filled with the new data.
Fixes #229.

Fix shadow bars problem

---

spec/widgets/histogram/content-view.spec.js
src/widgets/histogram/content-view.js

If a widget is filtered, and another histogram belongs to the same layer, stats should be updated.
Also, if bins attribute is updated, stats should be reset too.
Fixes #235.

Fixing problem with selected data in histogram, after other widget is filtered

---

spec/widgets/category/content-view.spec.js
spec/widgets/category/stats-view.spec.js
src/widgets/category/content-view.js
src/widgets/category/stats/stats-view.js

Possibility to change the visibility of the category stats view, right now, if show_stats was false, the view was not added and there was not possibility to show it again.
Fixes #246.
CR: @javierarce

Category stats view always rendered and then checking visibility if show_stats is enabled or not

---

src/widgets/histogram/chart.js
src/widgets/histogram/content-view.js
src/widgets/time-series/content-view.js
src/widgets/time-series/histogram-view.js
src/widgets/time-series/torque-content-view.js
src/widgets/time-series/torque-histogram-view.js

Fixes #254 
Bonus fix: Don't pause the torque animation on data change/range reset :dancer: 
@javierarce review, please :bow:

Fix 254 Time-series widget renders all data in chart initially instead of only the visible data in bbox

---

src/widgets/histogram/content-view.js

There is a problem with the CLEAR button, and the steps for replicating it are in #258 ticket. We have created a function to reset the state of the histogram widget (origin of the problem). How does it sound @javierarce?
CR: @javierarce.
cc @javisantana 
Fixes #258.

Reset histogram widget when user clicks over CLEAR button

---

spec/widgets/histogram/content-view.spec.js
src/widgets/histogram/chart.js

Preventing this problem in the zoomed histogram:
Before:
After: 
cc @javierarce

Use original data for creating the chart Y scale

---

examples/time-series-widget.html
package.json
spec/dashboard-below-map-view.spec.js
spec/widgets/histogram/chart.spec.js
spec/widgets/histogram/content-view.spec.js
spec/widgets/time-series/content-view.spec.js
spec/widgets/time-series/torque-content-view.spec.js
src/widgets/histogram/chart.js
src/widgets/histogram/content-view.js
src/widgets/time-series/content-view.js
src/widgets/time-series/histogram-view.js
src/widgets/time-series/time-series-header-view.js
src/widgets/time-series/time-series-header.tpl
src/widgets/time-series/torque-content-view.js
src/widgets/time-series/torque-header-view.js
src/widgets/time-series/torque-histogram-view.js
src/widgets/time-series/torque-render-range-info-view.js

Basically, after [this change](https://github.com/CartoDB/cartodb.js/pull/1181) in CartoDB.js, there is a new way to obtain all the data of the widget. That means we need to change several things in the histogram `content-view` and `chart` classes. I've tried to keep things as they are and only touch affected parts. I'd like to know your opinion @javierarce before keep going.
cc @viddo @javisantana 
Pending things:
Overall, fixes https://github.com/CartoDB/cartodb.js/issues/1179.
CR: @javierarce

Changing way to use original data within histogram in order to fix 'vector histograms'

---

src/widgets/widget-view.js

As we decided when we talked about necessary analysis use cases, if a layer is not visible, widgets can be added and they will be visible.
cc @javierarce @alonsogarciapablo @rochoa

Don't take into account layer visibility in order to show widget view

---

src/widgets/histogram/chart.js
src/widgets/time-series/torque-render-range-info-view.js
src/widgets/time-series/torque-time-slider-view.js
themes/scss/widgets/list.scss

We were using `nice()` d3 function, which rounds values. Turns out it was rounding our dates to the end of the year, and x-axis labels and torque selections appeared wrong.
In short, nice function, not nice :dancer:.
CR: @alonsogarciapablo 
Fixes #302.

Rounding dates within date histogram

---

spec/widgets/auto-style/category.spec.js
spec/widgets/auto-style/histogram.js
spec/widgets/category/category-colors.spec.js
src/widgets/auto-style/auto-styler.js
src/widgets/auto-style/category-colors.js
src/widgets/auto-style/histogram.js
src/widgets/category/category-widget-model.js

@javisantana @rochoa 
- Corrects typo in turbocartocss string for histogram-markers in vector (fixes #318).
- Prevents maps from reinstantiating when category auto style is on (fixes #319).
- Freezes assignment of new colours when auto style is on with category.
- Uses indices instead of geometry type names (fixes #316).

Autostyle fixes

---

spec/api/dashboard.spec.js
src/api/dashboard.js

In https://github.com/CartoDB/cartodb/issues/7445, we need a public reference to the view, in order to change the background color of the dashboard view when we are editing.
cc @xavijam

Export reference to the dashboard view.

---

src/api/url-helper.js

State strings in URLs seem to be URLencoded twice, because the library that we use to parse URLs already does the encoding internally. I'm just removing our call here.
@xavijam

Only encodes state string once

---

src/widgets/histogram/chart.js

Using offsetX was causing the `_getBarIndex` to return always 0.
Fixes #373 
CR @javierarce 🙌

Uses layerX instead of offsetX to calculate clicked bar index

---

spec/widgets/auto-style/histogram.js
src/widgets/auto-style/auto-styler.js
src/widgets/auto-style/category.js
src/widgets/auto-style/histogram.js

Notice that this applies to turbo-carto and static marker size rules, like the following:
```
marker-width: ramp([col],10, 30, 'jenks');
```
or
```
marker-width: 10;
```

Keeps marker widths on autostyle 

---

spec/widgets/auto-style.spec.js
spec/widgets/auto-style/category.spec.js
spec/widgets/auto-style/histogram.js
spec/widgets/category/category-widget-model.spec.js
spec/widgets/category/search-title-view.spec.js
src/widgets/auto-style/auto-styler.js
src/widgets/auto-style/category.js
src/widgets/auto-style/histogram.js
src/widgets/category/category-widget-model.js
src/widgets/histogram/histogram-widget-model.js

This gets rid of all the problems we've had related to cartocss changing dramatically when hitting autostyle. Now, instead of using predefined templates, we just modify some lines in the cartocss and pass it to the tiler as is.
@javisantana @makella

Inverting the autostyle workflow so styles aren't rewritten, but modified.

---

spec/api/create-dashboard.spec.js
src/api/create-dashboard.js

`createDashboard` was throwing an error, which was preventing the UI from being rendered.
Changes:
- createDashboard doesn't throw error and forwards error to the callback instead.
- Usage of `vis.instantiateMap` now gets an object with `success` and `error` callbacks instead of using `vis.done` and `vis.error` (which were not working). See: https://github.com/CartoDB/cartodb.js/pull/1334
@xavijam sounds good?

createDashboard handles errors diferently

---

src/widgets/histogram/histogram-widget-model.js
src/widgets/widget-model.js

Sometimes the values returned by the tiler differ from the ones in the dataview by decimal positions. This isn't really solving the problem, but it is a hotfix to avoid setting wrong values in the state.
Fixes https://github.com/CartoDB/cartodb/issues/8460
@javisantana

Rounds default numeric values

---

src/dashboard-menu-view.js
src/dashboard-menu-view.tpl

Twitter can't share an url super long (probably due to the state url feature), so let's share in Facebook and Twitter urls without params.
CR: @javisantana 
cc @piensaenpixel

Adding urls without params + target blank for user info

---

src/widgets/dropdown/widget-dropdown-view.js
src/widgets/histogram/chart.js
src/widgets/histogram/content-view.js

- Close #383 
- Remove unnecessary bind to normalized on initialize function.
- avoid to re-render the widget when activating/deactivating normalisation (was a pending enhancement)
- Showing stats after activating/deactivating normalization
- Refactors make _resetWidget making use of _updateStats

Fixes with Normalize

---

spec/widgets/time-series/torque-content-view.spec.js
spec/widgets/time-series/torque-time-slider-view.spec.js
src/api/dashboard.js

This disables widget state until [the issues with it](https://github.com/CartoDB/deep-insights.js/issues/416) are fixed. Until then, only map related state is shared (i.e, viewport).
Please CR @xavijam

Disable widget state

---

grunt-tasks/browserify.js

It fixes the problem we have right now with the bundle generation.
cc @nobuti

Using proper dependencies for browserify-resolutions

---

spec/widgets/auto-style/category.spec.js
spec/widgets/auto-style/style-utils.spec.js
src/widgets/auto-style/category.js
src/widgets/auto-style/histogram.js
src/widgets/auto-style/style-utils.js

We are replacing the attrs in other way. This fix #457 issue.
- Mark the attr to change
- Remove all of them
- Remove empty layers or conditions
- Change the mark with the new value of the attr
I've put the functional code just above, but it is not reusable and this is not a good place for it. We have to move it to a better place aligned with the project architecture to allow reusability and a better understanding.
This is a temporal solution, waiting for a better one using cartocss parser.
NOTE: I have to add tests to this PR, don't merge! 🙂 
cc @javisantana & @alonsogarciapablo

Complete cleaning for repetitives symbolizers fix #457

---

spec/widgets/auto-style.spec.js
spec/widgets/category/category-widget-model.spec.js
spec/widgets/category/item-view.spec.js
spec/widgets/category/search-title-view.spec.js
spec/widgets/histogram/histogram-widget-model.spec.js
spec/widgets/widget-model.spec.js
src/api/create-dashboard.js
src/api/dashboard.js
src/widgets-service.js
src/widgets/histogram/chart.js
src/widgets/widget-model.js

This PR allow deactivate the autostyle button from widgets with the `autoStyle` flag passed as option to createDashboard function.
If this option is not present, the autoStyle feature is disabled by default.

Add opts.autoStyle flag

---

src/api/dashboard.js
src/widgets-service.js
src/widgets/widgets-collection.js

In order to trigger the bindings properly when adding new widgets, we need to check if the initial
dataviews instantiation has already happened. In this scenario, we need to apply bindings without
waiting this event.
CR @donflopez 
cc @saleiva @javisantana

Track if dataviewsFetched happened already when adding new widgets.

---

src/widgets/histogram/chart.js

Because we used to have that regexp waiting for a translate like `translate(100, 100)` but in Microsoft Edge it returned only `translate(100)`, so it was not working and throwing an error.
cc @jsanz
Fixes #495.

Fixed problem with translate parsing in Microsfot Edge

---

src/dashboard-sidebar-view.js

This PR refactor the way we handle actions when the viewport reaches different breakpoints. Also, it introduces the new breakpoints defined in https://github.com/CartoDB/cartodb/pull/10485
CR @hacheka 
cc @xavijam @piensaenpixel

Match media for handle breakpoints at js level.

---

src/widgets/auto-style/histogram.js

This PR fixes a minor issue for histogram and autostyle. For old widgets (before new auto style), the custom style doesn't exist, so we need to check if exists before to test it's custom.

Make sure styles exist when checking it's custom.

---

spec/widgets/category/category-widget-model.spec.js
src/widgets/category/category-widget-model.js

This problem is related with https://github.com/CartoDB/cartodb/issues/11166. We can't update auto-style colors when the feature is disabled. That throws an error and makes the app fail.
**STT**
- Basically the same steps described in https://github.com/CartoDB/cartodb/issues/11166.
Uploading to ded02 in order to be tested.

Don't update auto-style colors when the feauture is disabled

---

examples/dynamic_widgets.html
package.json
spec/widgets/histogram/chart.spec.js
spec/widgets/histogram/content-view.spec.js
spec/widgets/time-series/content-view.spec.js
spec/widgets/time-series/torque-content-view.spec.js
spec/widgets/time-series/torque-time-slider-view.spec.js
spec/widgets/widget-model.spec.js
src/widgets/histogram/chart.js
src/widgets/time-series/torque-histogram-view.js
src/widgets/widget-model.js
themes/scss/widgets/themes/light.scss

It represents the colors applied with the auto style in the histogram bars.
Related ticket:  https://github.com/CartoDB/cartodb/issues/11095.
**What should you test?**
Having an account with auto-style flag enabled:
- Applying the autostyle over a **histogram widget** should represent the same colors in the histogram bars.
- Disabling autostyle should remove the autostyle colors over the bars.
- Having applied the autostyle, change the number of bins/buckets of the widget and look if the widget is refreshed with the new bins and with the autostyle colors applied over the bars.
- Disable the autostyle and check that bars are back to the default color.
- Apply the autostyle over a histogram widget, check if the colors are ok and then move the map in order to change the widget bars height, …

Represent auto-style colors 

---

spec/widgets/auto-style/category.spec.js
src/widgets/auto-style/category.js

Ticket: cartodb/cartodb#11246.
Changing way to escape quotes with auto-style, following the same way we use within Builder and categories.
**Things to test:**
Check the ticket, because there is a good example there, but in any case:
- Create a map with a layer where the data contains single and double quotes.
- Add a category widget using the column where those single and double quotes are present.
- Autostyle that widget.

11246 issue

---

spec/widgets/category/search-title-view.spec.js
spec/widgets/histogram/chart.spec.js
spec/widgets/histogram/histogram-title-view.spec.js
spec/widgets/widget-model.spec.js
src/widgets/auto-style/histogram.js
src/widgets/category/category-widget-model.js
src/widgets/category/title/search-title-view.js
src/widgets/histogram/chart.js
src/widgets/histogram/content-view.js
src/widgets/histogram/histogram-title-view.js
src/widgets/widget-model.js

Problem coming from: https://github.com/CartoDB/cartodb-management/issues/4815, and reproduced here https://github.com/CartoDB/deep-insights.js/issues/513.
**THINGS TO TEST**
- Apply a custom CartoCSS with icons (not common circles or anything), check that autostyle button disappears.
- Unapply custom CartoCSS, apply a standard one and check that autostyle button is back.
- Check that other combinations are not affected, like testing it with layer visibility, if it is allowed, etc.
- Check that, if a histogram widget is added when the cartocss doesn't provide any [marker-fill or polygon-fill or line-color], autostyle button doesn't appear. After that, reset the cartocss, provide a simple one, and autostyle button should appear again, click it and check that bars appear colored properly.
- …

Don't offer auto-style if it is not possible to auto-style due to a custom cartocss with image

---

src/widgets/category/list/items-view.js
themes/scss/widgets/list.scss

There is a problem right now with the category widget placeholder, it really gets me mad:
So, when it is fixed:
- Desktop:
- Mobile:

Fixed placeholder styles

---

themes/scss/widgets/default.scss

Same problem described for the map [here](https://github.com/CartoDB/cartodb.js/pull/1580) but happening with chart widgets (histogram and time-series).
cc @nobuti @piensaenpixel @alonsogarciapablo

Fixing problem related with Surface map pan

---

src/widgets/time-series/time-series-header-view.js
src/widgets/time-series/torque-time-info-view.js

Related ticket: https://github.com/CartoDB/cartodb/issues/11174
We were rounding (nicely) selection dates, and it was causing problems in the way we calculate selected ranges. 
An example with the same dataset, before and after:
Before:
After:
cc @michellechandra  @zingbot

Removed unnecessary nice function from time-series header view

---

src/widgets/auto-style/histogram.js

This is a change to the classification method we use behind the scenes for the Histogram widget with a F shaped distribution. I had originally set it to quantiles but after more thought, equal is more appropriate.
Please let me know if you have any questions
cc @saleiva

change of classification method for F shape distribution

---

themes/scss/widgets/default.scss

Related: https://github.com/CartoDB/cartodb/issues/11754
Basically that, right now the loader for the time-series widget is visible although the loader is inactive. With this change it should be 👌 . It is also applied for any widget, just in case. 
Checked that tooltips work properly.

Fixed problem with loader position in time-series widget

---

spec/widgets/histogram/chart.spec.js
src/widgets/histogram/chart.js

Related ticket: https://github.com/CartoDB/cartodb/issues/11798
Steps to reproduce already described there ^^^. But good ones also are:
- Create a map with a histogram widget where the there is at least a bucket without data.
Example: 
- Select the bin or bins without data and zoom into it/them.
Example:
- JS error appeared, now zoomed histogram should be empty.

When dataBin is not defined it should not return anything

---

spec/api/create-dashboard.spec.js
spec/api/dashboard.spec.js
src/api/create-dashboard.js
src/api/dashboard.js
src/widgets-service.js

We have agreed a better way to "report" when a state change has happened. So any other elements can subscribe to it.
Related PR in CARTO Builder: https://github.com/CartoDB/cartodb/pull/11901#pullrequestreview-30460811

Replace way to trigger widget state changes

---

src/api/dashboard.js

Something we could use [here](https://github.com/CartoDB/cartodb/blob/866546c592549848b71e388803a0c4553c650526/lib/assets/core/javascripts/cartodb3/deep-insights-integrations.js#L722) to avoid that "train wreck"... What do you think @xavijam?

Adds dashboard#reloadMap

---

spec/widgets/category/category-widget-model.spec.js
spec/widgets/category/search-title-view.spec.js
spec/widgets/histogram/histogram-title-view.spec.js
spec/widgets/widget-model.spec.js
src/widgets/widget-model.js

If a widget has set the autoStyle, but the map in the instantiation phase has no data to show, the dataview linked to that widget has no data either, so the styles generated for the autoStyle are no properly formatted.
This PR is related to https://github.com/CartoDB/cartodb/issues/11838 but this is happening in production right now.
@xavijam @donflopez

Avoid to generate styles for autostyle if dataview has no data.

---

package.json
spec/widgets/histogram/content-view.spec.js
spec/widgets/time-series/time-series-header-view.spec.js
spec/widgets/time-series/torque-header-view.spec.js
src/widgets/time-series/animation-template.tpl
src/widgets/time-series/content-view.js
src/widgets/time-series/time-series-header-view.js
src/widgets/time-series/time-series-header.tpl
src/widgets/time-series/torque-content-view.js
src/widgets/time-series/torque-header-view.js

Part of https://github.com/CartoDB/cartodb/issues/12179
In this PR we've added the visual hint of how many items are selected in the time-series widget.

12179 time series selected text

---

src/widgets/category/title/search-title-template.tpl
src/widgets/formula/template.tpl
src/widgets/histogram/content.tpl

reopening https://github.com/CartoDB/deep-insights.js/pull/552 after discussion https://github.com/CartoDB/cartodb/pull/12369#issuecomment-313396595
this just makes the analysis type darker

widgets: source: darken

---

package.json
spec/widgets/widget-model.spec.js
src/widgets/widget-model.js

re: https://github.com/CartoDB/cartodb/issues/12394
adding `widget_color_changed` attribute to the widget definition model style, because otherwise when selecting the category in the widget, it prevails as the widget color is persisted
I didn't quite like the hardcoded color check but I've seen it in other parts of deep insights codebase. Another workaround would be running a migration in the widgets table to add the `widget_color_changed` when the widget color won't match the default color

widget color changed

---

themes/scss/map/_dashboard-info.scss

Related to: https://github.com/CartoDB/support/issues/865
The problem was the menu was displayed but with `opacity: 0;`, and it sits on top of the first checkbox if the Layer Selector option is enabled.
The menu has a class called `CDB-Dashboard-hideMobile` which doesn't exist, I just added it to the `max-width: 759px` media-query.

Add .CDB-Dashboard-hideMobile class

---

package.json
spec/widgets/histogram/content-view.spec.js
src/widgets/histogram/content-view.js
src/widgets/histogram/content.tpl

This PR aims to fix https://github.com/CartoDB/cartodb/issues/12477 hiding the markup when there are no nulls defined.

Show null if model says so.

---

spec/widgets/time-series/histogram-view.spec.js
src/widgets/time-series/content-view.js
src/widgets/time-series/histogram-view.js

Related to https://github.com/CartoDB/cartodb/issues/12576
This PR implements applying the filter in time-series widgets (no animated) when loading the map.
Related PR at `cartodb`: https://github.com/CartoDB/cartodb/pull/12577

Listen to initial state changes at timeseries view

---

src/widgets/time-series/placeholder.tpl
src/widgets/time-series/torque-histogram-view.js
themes/scss/widgets/_default.scss
themes/scss/widgets/_time-series.scss

Related to: https://github.com/CartoDB/cartodb/issues/12609
Acceptance:
Create a new map with animated styles, go to the embed map in responsive mode, the chart should be inside the container and not getting out of the viewport (see issue).

Use width: auto when time-series is animated

---

package.json
spec/dashboard-below-map-view.spec.js
spec/widgets/histogram/chart.spec.js
spec/widgets/time-series/histogram-view.spec.js
spec/widgets/widget-model.spec.js
src/api/dashboard.js
src/dashboard-below-map-view.js
src/dashboard-sidebar-view.js
src/dashboard-view.js
src/widgets/histogram/chart.js
src/widgets/time-series/histogram-view.js
src/widgets/widget-model.js

The chart inside an histogram (time-series) is forced to resize when a widget is added or removed:
I have added the public method "forceResize" to the dashboard, to enable its use from the Builder and also to avoid window.bind('resize') in the chart.

Force resize when a widget is added/removed and there is a time-series

---

src/widgets/histogram/chart.js

Related to: https://github.com/CartoDB/cartodb/issues/12661
The handlers where getting stuck in the middle of the buckets, debugging I found that if you moved the handler to the first half of the next bucket, it should move where it was previously, which means the same indexes, so the backbone model didn't trigger any changes which lead to the function which calculates the handler position not being called.
The proposed solution is to make the changes silent, and the trigger the event manually.

Trigger indexes change event even if they don't change

---

spec/widgets/category/content-view.spec.js
spec/widgets/formula/content-view.spec.js
spec/widgets/histogram/content-view.spec.js
spec/widgets/time-series/content-view.spec.js
spec/widgets/time-series/torque-content-view.spec.js
src/util/escape-html.js
src/widgets/category/title/search-title-view.js
src/widgets/formula/content-view.js
src/widgets/histogram/content-view.js
src/widgets/time-series/content-view.js
src/widgets/time-series/torque-content-view.js

Related to: https://github.com/CartoDB/cartodb/issues/12322
Changes:
- Escape HTML in source layerName for all the widgets. This change prevents XSS (https://github.com/CartoDB/bug-bounty/issues/152)
- Refresh widgets when a Layer's title changes, to update its sources

Escape HTML content in widgets source

---

src/widgets/histogram/chart.js
themes/scss/widgets/_chart.scss
themes/scss/widgets/_default.scss

This PR improves the histograms rendering. It's related to https://github.com/CartoDB/cartodb/issues/12217. Right now, a histogram has a few issues:
- In Safari, all bars are rendered without spacing, the worst scenario occurs for time-series.
- When a user applies a zoom to the browser, the spacing is not consistent between bars. This is for all browsers.

Glitches for histogram charts

---

package.json
src/widgets/histogram/content-view.js

Related to https://github.com/CartoDB/cartodb/issues/12945
When the user clicks on `clear` to zoom out, the data was the one of the zoomed in. We should refetch the dataviewmodel data.

Fetch dataview data on zoom out

---

themes/scss/widgets/_search.scss

Related to: https://github.com/CartoDB/support/issues/1074
When using `flex-grow(2)` the autoprefixer applied the rule `-ms-flex: 2 0 auto`, which means we're using `flex-shrink: 0`, and somehow it breaks. Using `flex-shrink: 1` which should be the initial value [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink) it works.

Fix flex-grow in IE11

---

package.json
spec/formatter.spec.js
spec/widgets/histogram/chart.spec.js
spec/widgets/time-series/torque-time-slider-view.spec.js
src/formatter.js
src/widgets/histogram/chart.js
src/widgets/time-series/time-series-header-view.js
src/widgets/time-series/torque-time-info-view.js
src/widgets/time-series/torque-time-slider-view.js

Related to https://github.com/CartoDB/cartodb/issues/13070
----
Due to changes made in https://github.com/CartoDB/cartodb.js/pull/1894 now we must format timestamps taking into account the dataview offset.

Format timestamps with offset

---

src/widgets/category/title/search-title-template.tpl
src/widgets/category/title/search-title-view.js
src/widgets/formula/content-view.js
src/widgets/formula/template.tpl
src/widgets/histogram/histogram-title-template.tpl
src/widgets/histogram/histogram-title-view.js
src/widgets/time-series/time-series-header-view.js
src/widgets/time-series/time-series-header.tpl

re: https://github.com/CartoDB/cartodb/issues/13095
- cartodb: https://github.com/CartoDB/cartodb/pull/13102
- deep-insights: https://github.com/CartoDB/deep-insights.js/pull/627
---
added "more options" tooltip and changed literals in auto style tooltips

add toltips to widgets

---

grunt-tasks/browserify.js
package.json

Related issue: https://github.com/CartoDB/cartodb.js/issues/1911
* Include explicitly the camshaft-reference file in the browersify bundle since it can not handle dynamic requires.
NOTE: when changing to webpack this is not needed.

Optimize bundle size

---

package.json
src/widgets/histogram/chart.js
themes/scss/widgets/themes/_light.scss
yarn.lock

Related to #640 
- Deep-insights.js https://github.com/CartoDB/deep-insights.js/pull/641
- CartoDB https://github.com/CartoDB/cartodb/pull/13275
----
This PR adds the missing hover and selected state colors to Widgets.
Based on https://user-images.githubusercontent.com/14546701/32537554-50cc906e-c463-11e7-9e20-5c11a5ce4a32.png
As I removed `tinycolor` dependency and it is not used anywhere else, do you want me to remove it from the project?
- Check that `Bar Color Green with 16% black` color is applied when mouse is over any item
- Check that `Bar Color Dark` is applied when any item is selected
- Check that `Bar Color Green with 16% black` color is applied when mouse is over any bar
- Check that `Bar Color Dark` is applied when there is a range selected

Add missing hover and selected state colors to Widgets

---

package.json
spec/formatter.spec.js
src/formatter.js

Related to https://github.com/CartoDB/support/issues/1071
----
This PR shows decade labels in time series widget.

Display decades in time series widget

---

spec/widgets/auto-style/category.spec.js
src/widgets/auto-style/category.js

Cherry-picked from https://github.com/CartoDB/deep-insights.js/pull/648
Support auto-style from numeric categories automatically (CartoDB/support#611)

Category auto-style: Support numeric names
